In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define activation functions and their derivatives
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Load Iris Dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# One-hot encode the target labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define neural network structure
input_size = X_train.shape[1]
hidden_size = 5  # You can experiment with different hidden layer sizes
output_size = y_train.shape[1]

# Initialize weights and biases
np.random.seed(1)
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Forward propagation
def forward_propagation(X):
    Z1 = np.dot(X, W1) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)
    return A1, A2

# Compute loss
def compute_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Backpropagation
def back_propagation(X, y, A1, A2):
    global W1, b1, W2, b2

    dZ2 = A2 - y
    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * sigmoid_derivative(A1)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

# Training the neural network
epochs = 10000
learning_rate = 0.1

for epoch in range(epochs):
    A1, A2 = forward_propagation(X_train)
    back_propagation(X_train, y_train, A1, A2)
    if epoch % 1000 == 0:
        loss = compute_loss(y_train, A2)
        print(f'Epoch {epoch}, Loss: {loss}')

# Test the neural network
A1, A2 = forward_propagation(X_test)
print("Predictions (one-hot encoded):")
print(np.round(A2))

# Convert one-hot encoded predictions back to class labels
predicted_labels = np.argmax(A2, axis=1)
true_labels = np.argmax(y_test, axis=1)

print("Predicted labels:")
print(predicted_labels)
print("True labels:")
print(true_labels)

# Calculate accuracy
accuracy = np.mean(predicted_labels == true_labels)
print(f'Accuracy: {accuracy}')



/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch 0, Loss: 0.16233658028944384
Epoch 1000, Loss: 0.006875968170743966
Epoch 2000, Loss: 0.0068197021161182335
Epoch 3000, Loss: 0.006728749768796058
Epoch 4000, Loss: 0.00014215902582937848
Epoch 5000, Loss: 1.9029186044810387e-05
Epoch 6000, Loss: 6.623044012736295e-06
Epoch 7000, Loss: 3.230520861238316e-06
Epoch 8000, Loss: 1.8763447728976266e-06
Epoch 9000, Loss: 1.212432569977163e-06
Predictions (one-hot encoded):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
Predicted labels:
[0 1 1 0 1 1 2